version: '3'

services:

  telegram_api:
    container_name: telegram_api
    build: .
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - 9080:80
    command: ["python", "/app/telegram/manage.py", "runserver", "0:80"]
    environment:
      DEBUG: 'True'

  telegram_celery:
    container_name: telegram_celery
    build: .
    working_dir: /app/telegram
    command: ["celery", "-A", "telegram", "worker", "-l", "info"]
    restart: unless-stopped
    volumes:
      - .:/app
    depends_on:
      - telegram_redis

  telegram_beat:
    container_name: telegram_beat
    build: .
    working_dir: /app/telegram
    command: ["celery", "-A", "telegram", "beat", "-l", "info"]
    restart: unless-stopped
    volumes:
      - .:/app
    depends_on:
      - telegram_redis

  telegram_redis:
    container_name : telegram_redis
    image: redis:5.0.8
    restart: unless-stopped
